[workspace]
resolver = "2"
members = [
    "rp2040-hal",
    "boards/feather-rp2040",
    "boards/qt-py-rp2040",
    "boards/itsy-bitsy-rp2040",
    "boards/kb2040",
    "boards/pico",
    "boards/pico-explorer",
    "boards/pico-lipo-16mb",
    "boards/adafruit-macropad",
    "boards/pro-micro-rp2040",
]

[patch.'https://github.com/rp-rs/rp-hal.git']
rp2040-hal = { path ="./rp2040-hal" }

[patch.crates-io]
rp2040-hal = { path ="./rp2040-hal" }
