[workspace]
resolver = "2"
members = [
    "rp2040-hal",
    "boards/adafruit-feather-rp2040",
    "boards/adafruit-qt-py-rp2040",
    "boards/adafruit-itsy-bitsy-rp2040",
    "boards/adafruit-kb2040",
    "boards/pico",
    "boards/pimoroni-pico-explorer",
    "boards/pimoroni-pico-lipo-16mb",
    "boards/adafruit-macropad",
    "boards/sparkfun-pro-micro-rp2040",
]

[patch.'https://github.com/rp-rs/rp-hal.git']
rp2040-hal = { path ="./rp2040-hal" }

[patch.crates-io]
rp2040-hal = { path ="./rp2040-hal" }
