on: [push, pull_request]
name: Clippy check
jobs:
  clippy_check:
    runs-on: ubuntu-20.04
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: thumbv6m-none-eabi
          components: clippy
      - run: cargo clippy --workspace --examples -- -Dwarnings
