on: [push, pull_request]
name: Check rp235x-hal-examples on Arm
env:
  PACKAGE: rp235x-hal-examples
  TARGET: thumbv8m.main-none-eabihf
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ env.TARGET }}
      - name: Build
        run: cd ${PACKAGE} && cargo build --target=${TARGET}
  udeps:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-01-30
          target: ${{ env.TARGET }}
      - name: Install cargo-udeps
        run: |
          curl -sSL https://github.com/est31/cargo-udeps/releases/download/v0.1.45/cargo-udeps-v0.1.45-x86_64-unknown-linux-gnu.tar.gz | tar xvzf - --strip-components=2 -C ~/.cargo/bin ./cargo-udeps-v0.1.45-x86_64-unknown-linux-gnu/cargo-udeps
      - name: Run cargo-udeps
        run: cd ${PACKAGE} && cargo udeps --target=${TARGET}
  msrv:
    name: Verify build on MSRV
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.77
          target: ${{ env.TARGET }}
      - name: Use older version of regex
        run: cd ${PACKAGE} && cargo update -p regex --precise 1.9.3
      - name: Build on MSRV
        run: cd ${PACKAGE} && cargo build --target=${TARGET}
  fmt:
    runs-on: ubuntu-20.04
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check format
        run: cd ${PACKAGE} && cargo fmt -- --check
  clippy:
    runs-on: ubuntu-20.04
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ env.TARGET }}
          components: clippy
      - name: Run cargo clippy
        run: cd ${PACKAGE} && cargo clippy --target=${TARGET}
